import FWCore.ParameterSet.Config as cms 
 
process = cms.Process("Ana") 
process.load("FWCore.MessageService.MessageLogger_cfi")
process.load('Configuration.StandardSequences.MagneticField_38T_cff')
process.load("CondCore.DBCommon.CondDBSetup_cfi")
process.load("Configuration.StandardSequences.Geometry_cff")
process.load("Geometry.CaloEventSetup.CaloGeometry_cfi")
process.load("Geometry.CaloEventSetup.CaloTopology_cfi")

## # configure HLT
## process.load('L1TriggerConfig.L1GtConfigProducers.L1GtTriggerMaskTechTrigConfig_cff')
## process.load('HLTrigger/HLTfilters/hltLevel1GTSeed_cfi')
## process.hltLevel1GTSeed.L1TechTriggerSeeding = cms.bool(True)
## process.hltLevel1GTSeed.L1SeedsLogicalExpression = cms.string('0 AND (40 OR 41) AND (NOT 36) AND (NOT 37) AND (NOT 38) AND (NOT 39)')


## # Physics declared 
## process.skimming = cms.EDFilter("PhysDecl",
##    applyfilter = cms.untracked.bool(True)
## )


## process.primaryVertexFilter = cms.EDFilter("GoodVertexFilter",
##     vertexCollection = cms.InputTag('offlinePrimaryVertices'),
##     minimumNumberOfTracks = cms.uint32(1) ,
##     maxAbsZ = cms.double(20), 
##     maxd0 = cms.double(8) 
## )



#############   Set the number of events #############
process.maxEvents = cms.untracked.PSet(
    input = cms.untracked.int32(-1)
)




process.source = cms.Source("PoolSource",
    fileNames = cms.untracked.vstring(
'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_100.root',
'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_101.root',
'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_102.root',
'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_103.root',
'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_104.root',
#'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_105.root',
#'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_106.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_107.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_108.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_109.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_10.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_110.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_111.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_112.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_113.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_114.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_115.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_116.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_117.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_118.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_119.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_11.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_120.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_121.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_122.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_123.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_124.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_125.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_126.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_127.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_128.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_129.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_12.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_130.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_131.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_132.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_133.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_134.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_135.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_136.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_137.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_138.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_139.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_13.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_140.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_141.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_142.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_143.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_144.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_145.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_146.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_147.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_148.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_149.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_14.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_150.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_151.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_152.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_153.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_154.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_155.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_156.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_157.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_158.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_159.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_15.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_160.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_161.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_162.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_163.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_164.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_165.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_166.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_167.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_168.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_169.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_16.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_170.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_171.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_172.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_173.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_174.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_175.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_176.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_177.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_178.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_179.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_17.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_180.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_181.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_182.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_183.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_184.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_185.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_186.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_187.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_188.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_189.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_18.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_190.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_191.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_192.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_193.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_194.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_195.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_196.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_197.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_198.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_199.root',
'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_19.root'
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_1.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_200.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_201.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_202.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_203.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_204.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_205.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_207.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_208.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_209.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_20.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_210.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_211.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_212.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_213.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_214.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_215.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_216.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_217.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_218.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_219.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_21.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_220.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_221.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_222.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_223.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_224.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_225.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_226.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_227.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_228.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_229.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_22.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_230.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_231.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_232.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_233.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_234.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_235.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_236.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_237.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_238.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_239.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_23.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_240.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_241.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_242.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_243.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_244.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_245.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_246.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_247.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_248.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_249.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_24.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_250.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_251.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_252.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_253.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_254.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_255.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_256.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_257.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_258.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_259.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_25.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_260.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_261.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_262.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_263.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_264.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_265.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_266.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_267.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_268.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_269.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_26.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_270.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_271.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_272.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_273.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_274.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_275.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_276.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_277.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_278.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_279.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_27.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_280.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_281.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_282.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_283.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_284.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_285.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_286.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_287.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_288.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_289.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_28.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_290.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_291.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_292.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_293.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_294.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_295.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_296.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_297.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_298.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_299.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_29.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_2.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_300.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_301.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_302.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_303.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_304.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_305.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_306.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_307.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_308.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_309.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_30.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_310.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_311.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_312.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_313.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_314.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_315.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_316.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_317.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_318.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_319.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_31.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_320.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_321.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_322.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_323.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_324.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_325.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_326.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_327.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_328.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_329.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_32.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_330.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_331.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_332.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_333.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_334.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_335.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_336.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_337.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_338.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_339.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_33.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_340.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_341.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_342.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_343.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_344.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_345.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_346.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_347.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_348.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_349.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_34.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_350.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_351.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_352.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_353.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_354.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_355.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_356.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_357.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_358.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_359.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_35.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_360.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_361.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_362.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_363.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_364.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_365.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_366.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_367.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_368.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_369.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_36.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_370.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_372.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_373.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_374.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_375.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_376.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_377.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_378.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_379.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_37.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_380.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_382.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_383.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_384.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_385.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_386.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_387.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_388.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_389.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_38.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_390.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_391.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_392.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_393.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_394.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_395.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_396.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_397.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_398.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_399.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_39.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_3.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_400.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_401.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_402.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_403.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_404.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_405.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_406.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_407.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_409.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_40.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_410.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_411.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_412.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_413.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_414.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_415.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_416.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_417.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_418.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_419.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_41.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_420.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_421.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_422.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_423.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_424.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_425.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_426.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_427.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_428.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_429.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_42.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_430.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_431.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_43.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_44.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_45.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_46.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_47.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_48.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_49.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_4.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_50.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_51.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_52.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_53.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_54.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_55.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_56.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_57.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_58.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_59.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_5.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_60.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_61.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_62.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_63.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_64.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_65.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_67.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_68.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_69.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_6.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_70.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_71.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_72.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_73.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_74.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_75.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_76.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_77.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_78.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_79.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_7.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_80.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_81.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_82.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_83.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_84.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_85.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_86.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_87.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_88.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_89.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_8.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_90.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_91.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_92.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_93.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_94.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_95.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_96.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_97.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_98.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_99.root',
## 'dcache:/pnfs/cms/WAX/resilient/makouski/minBiasFiltered/SkimSuperClusters_9.root'
   )
)


 
process.MessageLogger.destinations = ['cout', 'cerr'] 
process.MessageLogger.cerr.FwkReport.reportEvery = 1000
 
#  SuperClusters  ################

#process.load("RecoEcal.EgammaClusterProducers.ecalClusteringSequence_cff")
process.load("RecoEcal.EgammaClusterProducers.hybridSuperClusters_cfi")
process.load("RecoEcal.EgammaClusterProducers.multi5x5SuperClustersWithPreshower_cfi")


process.EBSuperClusters = cms.EDFilter("SuperClusterSelector",
    src = cms.InputTag("hybridSuperClusters"),
    cut = cms.string('abs( eta ) < 1.4442')
)

process.EESuperClusters = cms.EDFilter("SuperClusterSelector",
    src = cms.InputTag("multi5x5SuperClustersWithPreshower"),
    cut = cms.string('abs( eta ) > 1.560 & abs( eta ) < 2.5')
)

process.allSuperClusters = cms.EDFilter("SuperClusterMerger",
   src = cms.VInputTag(cms.InputTag("EBSuperClusters"), cms.InputTag("EESuperClusters"))
)


process.sc_sequence = cms.Sequence( ( (process.hybridSuperClusters*process.EBSuperClusters) +
                                      (process.multi5x5SuperClustersWithPreshower*process.EESuperClusters) )* 
                                    process.allSuperClusters
                                    )


process.eff = cms.EDAnalyzer("ElectronEfficiency",
    SuperClusters = cms.InputTag('allSuperClusters'),
    jets                   = cms.string('ak5CaloJets'), 
    jetsID                 = cms.string('ak5JetID'),
    jetExtender            = cms.string('ak5JetExtender'),
    met                    = cms.string('met'),
    metNoHF                = cms.string('metNoHF'),
    hcalNoiseTag           = cms.InputTag('hcalnoise'),
    minJetPt               = cms.double(3.0), 
    HistOutFile = cms.untracked.string('histograms.root')
)


## process.p = cms.Path(
## 	process.hltLevel1GTSeed *process.skimming * process.primaryVertexFilter *
## 	process.sc_sequence *
##         process.eff
## 	)
process.p = cms.Path( process.sc_sequence * process.eff )
